### PR TITLE
Updated to Swift 4.

### PR DESCRIPTION
**Pull request by thibaultdm**

### CODE REVIEW

**Comment by lgauthier** [comment]
@thibaultdm Hey, it looks like the CI plan failed. I see that one thing you'll need to update is the .travis.yml file so that it specifies that the project should be built with Xcode 9 and new iOS 11 SDK and simulator. You can check out these commits from MetovaTestKit and DataManager to get an idea of what needs to be updated:

https://github.com/metova/MetovaTestKit/commit/b302acef718ff23cf193e6e7d9e036b4c153fc6d
https://github.com/metova/DataManager/commit/0a4f43406306da70c504ffa48407dc81c3c7ae41

**Comment by lgauthier** [comment]
@thibaultdm Looks like the build is failing because of SwiftLint. I believe Travis is just using whatever version of swiftlint is installed, and more recent versions of SwiftLint have a problem when double quotes are used to surround the regex for custom rules.

Ideally, I'd like to use a workspace for this project and set up CocoaPods so we can make SwiftLint a CocoaPods dependency so its version is managed. However, for now, I'm fine with just replacing the double quotes to single quotes if that's all it takes to pass SwiftLint.

**Comment by lgauthier** [comment]
@nhgrif You got any ideas on why these tests are randomly failing sometimes on Travis? I know the machines that these Travis builds run on tend to be slower so I'm guessing that has something to do with it. These tests use the async testing APIs for waiting for expectations and the timeout is zero, but it seems to me like that should be fine no matter how slow the machine is because the expectations should be fulfilled synchronously.

**Comment by thibaultdm** [comment]
@nhgrif not sure if you saw this

**Comment by nhgrif** [comment]
I'm not sure, but I'm fine upping the wait time if we believe they're just failing because of slow machines.

**Pull request merged**
