### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by johnslay**

### CODE REVIEW

**Comment by lgauthier** [comment]
@johnslay Is this ready to be merged now you think? Also, this swift-3 branch was branched off of master instead of develop. We'll want to merge to develop before merging to master, and you may have some merge conflicts merging to develop.

**Comment by lgauthier** [comment]
@johnslay Lets get this merged tomorrow.

**Comment by johnslay** [comment]
@lgauthier just merged develop into it. messed it up so the commit history looks weird but there was only a minor change.

**Comment by lgauthier** [comment]
@johnslay Ok, I think we can just re-point this PR to develop and then we should be good to merge.

**Comment by lgauthier** [comment]
@nhgrif Do you want to look over this at all before merging?

**Pull request merged**
